### PR TITLE
correct Indian time & add Sydney time for sunday meetings.

### PR DESCRIPTION
**Pull request by 0xharkirat**
Indian Time changed from 9 PM to 10 PM.
Sydney Time added.

### CODE REVIEW

**Comment by IshanGrover2004** [comment]
I'll close [mine PR](https://github.com/CCExtractor/website/pull/48). Since you have corrected it and added Sydney time as well

**Comment by 0xharkirat** [comment]
All good. Thanks.

**Comment by 0xharkirat** [comment]
Also added the link to automatically convert the meeting time to local time zone.  

image

**Comment by 0xharkirat** [comment]
Thanks team.

**Pull request merged**
